In [2]:
import numpy as np

In [1]:


vector1 = np.array([1,2])
vector2 = np.array([3,5])
print(vector1.shape)

vectoradd = vector1 + vector2 
print(vectoradd)

vectorsubb = vector1 - vector2 
print(vectorsubb)

vectormulti=vector1 * vector2 
print(vectormulti)

(2,)
[4 7]
[-2 -3]
[ 3 10]


In [7]:
import numpy as np

x= np.array([[15,10,5],
            [50,6,7]])



y=np.array([[5,8,7],
            [10,3,4]])
l=np.array([[5,8],
            [10,3],
            [4,7]])

print(x.shape)

add=x+y
sub=x-y
multiply=x*y
print(f'add:: {add} \n')
print(f'sub:: {sub}\n')
print(f'multiply:: {multiply}\n')

print(f'transpose :: {x.T}')
print(f'mean :: {np.mean(y)}')



(2, 3)
add:: [[20 18 12]
 [60  9 11]] 

sub:: [[10  2 -2]
 [40  3  3]]

multiply:: [[ 75  80  35]
 [500  18  28]]

transpose :: [[15 50]
 [10  6]
 [ 5  7]]
mean :: 6.166666666666667


In [12]:
x= np.array([[1,10,5],
            [50,6,7]])

print(x.shape)

l=np.array([[5,8],
            [10,3],
            [4,7]])

print(l.shape)

out=np.dot(x,l)

print(out)



(2, 3)
(3, 2)
[[195 185]
 [338 467]]


In [8]:

arrayd=np.array([1, 5,6 ,7])

print(arrayd.shape)

(4,)
